In [1]:
import pathlib
from argparse import ArgumentParser

import numpy as np
import pandas as pd
import torch as th
import sklearn as sk

from pytorch_lightning import seed_everything, Trainer

from torch_factorization_models.implicit_mf import ImplicitMatrixFactorization
from torch_factorization_models.movielens import MovielensDataset

### Load the dataset

In [2]:
movielens = MovielensDataset("/home/karl/Projects/datasets/ml-20m/")

In [3]:
preprocessor = movielens.preprocessor

In [4]:
user_xformer = preprocessor.named_transformers_['user_id']
item_xformer = preprocessor.named_transformers_['item_id']

### Set up the model and the splits

In [5]:
seed_everything(42)  # same seed used to create splits in training

42

In [6]:
# TODO: Figure out how to set the number of users and items

In [7]:
parser = ArgumentParser(add_help=False)
parser = Trainer.add_argparse_args(parser)
parser = ImplicitMatrixFactorization.add_model_specific_args(parser)

args = parser.parse_args(args=[])
args.num_users = 138287
args.num_items = 20720
# args.use_biases = False
args.embedding_dim = 32

args

Namespace(accumulate_grad_batches=1, amp_backend='native', amp_level='O2', auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, benchmark=False, beta1=0.9, beta2=0.999, check_val_every_n_epoch=1, checkpoint_callback=True, default_root_dir=None, deterministic=False, distributed_backend=None, early_stop_callback=False, embedding_dim=32, fast_dev_run=False, gpus=<function Trainer._gpus_arg_default at 0x7fb30798ae50>, gradient_clip_val=0, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0, log_gpu_memory=None, log_save_interval=100, logger=True, loss='hinge', max_epochs=1000, max_steps=None, min_epochs=1, min_steps=None, momentum=0.9, num_items=20720, num_nodes=1, num_processes=1, num_sanity_val_steps=2, num_users=138287, overfit_batches=0.0, overfit_pct=None, precision=32, prepare_data_per_node=True, process_position=0, profiler=None, progress_bar_refresh_rate=1, reload_dataloaders_every_epoch=False, replace_sampler_ddp=True, resume_from_checkpoint=

In [9]:
model = ImplicitMatrixFactorization(args)

state_dict = th.load("../models/38ov3g28-honest-lake-213.pt")

# preprocessor = state_dict['preprocessor']
del state_dict['preprocessor']

model.load_state_dict(state_dict)

<All keys matched successfully>

In [10]:
# user_encoder = sk.preprocessing.OrdinalEncoder()
# print(preprocessor)
# params = preprocessor['transformers'][0][1]
# print(params.categories_)
# user_encoder.set_params(**params)
# user_encoder

### Load movie data

In [11]:
movies_df = pd.read_csv("/home/karl/Projects/datasets/ml-20m/movies.csv")

movies_df[:10]

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   
5        6                         Heat (1995)   
6        7                      Sabrina (1995)   
7        8                 Tom and Huck (1995)   
8        9                 Sudden Death (1995)   
9       10                    GoldenEye (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy  
5                        Action|Crime|Thriller  
6                               Comedy|Romance  
7                           Adventure|Children  
8                                       Action  
9                    Action|Adventure|Thriller

### Define a function to retrieve similar movies

In [12]:
# model.use_biases = False

In [13]:
# def fetch_similar(df, movieId, k):
#     movieIds = th.tensor(item_xformer.transform([[movieId], [10]])).flatten()
#     print(movieIds)
#     topk_scores, topk_indices = model.similar_to_items(movieIds)
#     print(topk_scores, topk_indices)
#     similarIds = item_xformer.inverse_transform(topk_indices.t()[:,0:1].numpy()).flatten()
#     print(similarIds.flatten())
#     return df[df['movieId'].isin(similarIds)]
# #     return scores
# #     return similarIds

def fetch_similar(df, movieId, k):
    movieIds = th.tensor(item_xformer.transform([[movieId], [1]])).flatten()
#     print(movieIds)
    topk_scores, topk_indices = model.similar_to_items(movieIds, k=k)
    print(topk_scores)
    print(topk_indices)
#     similar_ids = topk_indices.t()[:,0:1].numpy().flatten()
    ids_to_transform = topk_indices.t()[:,0:1].numpy()
    print(ids_to_transform)
    similar_ids = item_xformer.inverse_transform(ids_to_transform).flatten()
    print(similar_ids.flatten())
#     return df.iloc[similar_ids, :]
    return df[df['movieId'].isin(similar_ids)]
#     return scores
#     return similarIds

### Try it out!

In [14]:
# A new hope - 260
# model.use_biases = False
model.use_biases = False
fetch_similar(movies_df, 3328, 50)

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9999, 0.9997, 0.9997, 0.9997, 0.9997, 0.9996, 0.9996, 0.9995, 0.9994,
         0.9994, 0.9994, 0.9994, 0.9993, 0.9993, 0.9993, 0.9992, 0.9992, 0.9991,
         0.9991, 0.9991, 0.9991, 0.9990, 0.9990, 0.9989, 0.9988, 0.9988, 0.9988,
         0.9987, 0.9987, 0.9987, 0.9987, 0.9987, 0.9984, 0.9984, 0.9984, 0.9984,
         0.9983, 0.9982, 0.9982, 0.9981, 0.9981, 0.9981, 0.9980, 0.9980, 0.9979,
         0.9979, 0.9978, 0.9977, 0.9976, 0.9976]])
tensor([[ 3863,  1566, 12104,  4525,  1817,  8980,  4175,  1702,  8862,  4887,
          

movieId                                              title  \
1568      1622                          Kicked in the Head (1997)   
1704      1773                      Tokyo Fist (Tokyo ken) (1995)   
1711      1782                                 Little City (1998)   
1732      1809                         Fireworks (Hana-bi) (1997)   
1819      1903                                  Hav Plenty (1997)   
2219      2304                           Love Is the Devil (1998)   
2458      2543                          Six Ways to Sunday (1997)   
2679      2765                             Acid House, The (1998)   
3093      3180                         Play it to the Bone (1999)   
3158      3245                I Am Cuba (Soy Cuba/Ya Kuba) (1964)   
3241      3328           Ghost Dog: The Way of the Samurai (1999)   
3428      3518                        End of Violence, The (1997)   
3656      3747                                  Jesus' Son (1999)   
3767      3860                           Opportunists, The (2000)   
3882      3976                                     Stardom (2000)   
3964      4058           Personals, The (Zheng hun qi shi) (1998)   
4045      4139                               No Man's Land (1987)   
4162      4256                    Center of the World, The (2001)   
4176      4271                             Eureka (Yurîka) (2000)   
4194      4289  City of Women, The (Città delle donne, La) (1980)   
4295      4390                         Rape Me (Baise-moi) (2000)   
4296      4391  Vertical Ray of the Sun, The (Mua he chieu tha...   
4457      4552                Tetsuo, the Ironman (Tetsuo) (1988)   
4545      4640                                     Brother (2000)   
4607      4702        Thomas in Love (Thomas est Amoureux) (2000)   
4823      4919                                      Subway (1985)   
4910      5006  Sex and Zen (Rou pu Tuan zhi tou Qing bao Jian...   
4972      5068      Beijing Bicycle (Shiqi sui de dan che) (2001)   
4975      5071                                   Maelström (2000)   
5220      5317  Girls Can't Swim (Filles ne savent pas nager, ...   
5326      5423                              Gangster No. 1 (2000)   
5728      5827                        Young Americans, The (1993)   
5751      5850               Road Games (a.k.a. Roadgames) (1981)   
5759      5858                         Soupe aux Choux, La (1981)   
6696      6806             Time and Tide (Seunlau Ngaklau) (2000)   
8831     26413  Snake in the Eagle's Shadow (Se ying diu sau) ...   
9027     26749                            Prospero's Books (1991)   
9170     27018  Fudoh: The New Generation (Gokudô sengokushi: ...   
9191     27081                                Claire Dolan (1998)   
9196     27095                            Hole, The (Dong) (1998)   
9637     31086  Battles Without Honor & Humanity (Jingi naki t...   
11185    47117   Tears of the Black Tiger (Fah talai jone) (2000)   
12118    55167           Tekkonkinkreet (Tekkon kinkurîto) (2006)   
12594    59053                                 Nathalie... (2003)   
12696    59814                                  Ex Drummer (2007)   
12903    61009                   Inside Paris (Dans Paris) (2006)   
13032    62254                     Funeral, The (Ososhiki) (1984)   
15216    77709            Sky Crawlers, The (Sukai kurora) (2008)   
16528    83525                         Outrage (Autoreiji) (2010)   
20741   101527            Into the White (Cross of Honour) (2012)   

                                         genres  
1568                               Comedy|Drama  
1704                               Action|Drama  
1711                             Comedy|Romance  
1732                                Crime|Drama  
1819                                     Comedy  
2219                                      Drama  
2458                                     Comedy  
2679                               Comedy|Drama  
3093                               Co

### Tests

In [15]:
model.use_biases = False
query_ids = th.tensor(list(range(2)))
scores, ids = model.similar_to_items(query_ids, k=3720)

# print(ids[:, 0])
# assert (ids[:, 0] == query_ids).all()

print(scores)
print(ids)

tensor([[9.9986e-01, 9.9973e-01, 9.9972e-01,  ..., 4.6388e-04, 4.6260e-04,
         4.6259e-04],
        [9.9999e-01, 9.9999e-01, 9.9999e-01,  ..., 2.9181e-01, 2.9150e-01,
         2.9123e-01]])
tensor([[    0,   148,   293,  ..., 11753,  2404,  4820],
        [10046,     1, 12666,  ...,  2556,  1698, 14795]])


In [16]:
model.use_biases = True
query_ids = th.tensor(list(range(100)))
scores, ids = model.similar_to_items(query_ids, k=5)

# print(ids[:, 0])
# assert (ids[:, 0] == query_ids).all()

print(scores)
print(ids)

tensor([[0.9999, 0.9997, 0.9997, 0.9997, 0.9997],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.9995, 0.9995, 0.9995, 0.9995],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.9999, 0.9999, 0.9998, 0.9998],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.9999, 0.9998, 0.9997, 0.9997],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
